/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/

module

public import Mathlib.NumberTheory.Padics.ProperSpace

/-!
# Dense embedded integers in the 2-adic integers

The embedded integers form a finitely generated dense additive subgroup of the
2-adic integers, used by the finite-index and character examples.
-/

@[expose] public section

namespace GroupTheoryTest.Topology.PadicDenseIntegers

local instance : Fact (Nat.Prime 2) := ⟨by decide⟩

/-- The additive subgroup of 2-adic integers generated by embedded integers. -/
noncomputable def padicIntegers : AddSubgroup ℤ_[2] :=
  (Int.castAddHom ℤ_[2]).range

/-- The embedded integers are finitely generated. -/
theorem padicIntegers_fg : padicIntegers.FG :=
  (AddGroup.fg_iff_addSubgroup_fg padicIntegers).mp
    (AddGroup.fg_range (Int.castAddHom ℤ_[2]))

/-- The embedded integers are dense in the 2-adic integers. -/
theorem padicIntegers_dense : Dense (padicIntegers : Set ℤ_[2]) := by
  simpa only [DenseRange, padicIntegers, AddMonoidHom.coe_range, Int.coe_castAddHom] using
    (PadicInt.denseRange_intCast (p := 2))

end GroupTheoryTest.Topology.PadicDenseIntegers

end
